# Generated by Django 4.2.7 on 2023-11-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='signup_token_created',
            field=models.DateTimeField(null=True),
        ),
    ]
