# Generated by Django 4.2.7 on 2023-11-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_signup_token_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
